# Generated by Django 4.2.30 on 2026-05-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('user_type', models.CharField(choices=[('user', 'User'), ('mua', 'Mua'), ('organization', 'Organization')], default='USER', max_length=20)),
                ('phone_number', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
