# Generated by Django 4.2.30 on 2026-05-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_customuser_address_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('makeupartist', 'Makeupartist'), ('organization', 'Organization')], default='user', max_length=20),
        ),
    ]
