# Generated by Django 4.2.30 on 2026-09-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='cPanel Webmail SMTP', help_text='Friendly label for this configuration', max_length=100)),
                ('smtp_host', models.CharField(default='mail.taliasplace.com', help_text='SMTP server host, e.g. mail.yourdomain.com', max_length=255)),
                ('smtp_port', models.IntegerField(default=465, help_text='SMTP port (usually 465 for SSL or 587 for TLS)')),
                ('security_mode', models.CharField(choices=[('SSL', 'SSL (Recommended for Port 465)'), ('TLS', 'TLS (Recommended for Port 587)')], default='SSL', max_length=10)),
                ('webmail_user', models.CharField(help_text='Webmail address used for SMTP login, e.g. info@yourdomain.com', max_length=255)),
                ('webmail_password', models.CharField(help_text='Password for webmail account', max_length=255)),
                ('default_from_email', models.CharField(blank=True, help_text="Sender header, e.g. Talia's Place <info@yourdomain.com>", max_length=255)),
                ('notification_recipient_email', models.EmailField(default='perpetualasadueze@gmail.com', help_text='Admin email to receive contact messages and booking notifications', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Designate this configuration as active for sending mail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMTP Setting',
                'verbose_name_plural': 'SMTP Settings',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
