# Generated by Django 4.2.30 on 2026-09-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="Talia's Place Alerts Bot", help_text='Friendly label for this bot connection', max_length=100)),
                ('bot_token', models.CharField(help_text='Telegram Bot Token from @BotFather (e.g. 7123456789:AAH...)', max_length=255)),
                ('chat_id', models.CharField(help_text='Your Telegram Chat ID or Channel ID where alerts should be sent', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Designate this Telegram bot configuration as active')),
                ('notify_on_contact', models.BooleanField(default=True, help_text='Receive instant notifications for new Contact form inquiries')),
                ('notify_on_booking', models.BooleanField(default=True, help_text='Receive instant notifications for new BookMe appointments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Setting',
                'verbose_name_plural': 'Telegram Settings',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
